### ISSUE TITLE
Blended image reading and writing formats!

### ISSUE THREAD

**Issue by IenLong** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#24]
As shown in the train_crop.py and val_crop.py files, images are read by scipy.misc.imread(...) while the cropped patches are saved by cv2.imwrite(...). This will make the cropped patches saved with the completely reverse channels of original images. As a result, the following data transformation for tfrecord based on these operations and finally involved in the training process will make learned model not consistent with the original images. While images are read by the way of cv2.imread(...), as in inference.py, eval.py, in the prediction phases!

**Comment by yangxue0827** [comment]
Yes, you are right. I did a transpose when I ran demo.py. Since the verification set is transposed just like the training set, there is no need to transpose the input image.In conclusion, it has no effect on the test results.
Anyway, I just forgot to modify train_corp.py and val_corp.py, which caused so much trouble. Thank you for reading carefully. @IenLong
